# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: the dropout ieatpants
email: brandon.eugene.miller@gmail.com
description:
  the home of the music of brandon eugene miller -- a struggling artists, accomplished physicist, sometime writer, and accidental developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ieatpants.github.io" # the base hostname & protocol for your site
twitter_username: ieatpants
github_username:  ieatpants

# Build settings
markdown: kramdown
